const moviesData = [
  {
    id: 1,
    title: "The Grinch",
    description: `In this festive tale, the Grinch, a bitter and lonely creature, plots to ruin Christmas for the cheerful inhabitants of Whoville, only to discover the true meaning of the holiday when he has a change of heart. The Grinch, who lives in isolation on Mount Crumpit, devises a plan to sneak into Whoville and steal Christmas by taking the Whos' Christmas trees, decorations, and presents. However, despite his efforts, he is moved by the Whos' joyous celebration, even without any material gifts. In the end, the Grinch's heart grows three sizes, and he returns all the stolen items, joining the Whos in their Christmas feast.`,
    posterURL: "https://fr.web.img4.acsta.net/c_310_420/pictures/18/10/12/14/23/1669146.jpg",
    rating: 6.4,
    trailerURL: "https://www.youtube.com/embed/vjnqABgxfO0",
  },
  {
    id: 2,
    title: "Mary",
    description: `In this timeless coming-of-age story, Mary is shunned following an otherworldly conception, and forced to flee when Herod's insatiable thirst for power ignites a murderous pursuit for the newborn. The story begins with the Virgin Mary's miraculous pregnancy, causing scandal in her village. As Mary flees with her betrothed Joseph to escape Herod's wrath, they are forced to travel across harsh landscapes to protect their child. Along the way, they face numerous obstacles, including betrayal, but ultimately find sanctuary in a humble stable, where Mary gives birth to the child who will grow up to become the Savior of the world.`,
    posterURL: "https://fr.web.img5.acsta.net/c_310_420/img/af/b5/afb58e2482e0bb48bbd92c02809ab3c2.jpg",
    rating: 5.2,
    trailerURL: "https://www.youtube.com/embed/d74vHvsACSs",
  },
  {
    id: 3,
    title: "Interstellar",
    description: `In this epic tale of survival, a team of astronauts ventures through a mysterious wormhole, battling the boundaries of space and time to secure humanity's future on a distant planet. Set in a dystopian future where Earth is dying, Cooper, a former NASA pilot, is recruited to lead a mission to find a new home for humanity. Along with a team of scientists, Cooper travels through a wormhole near Saturn to explore potentially habitable planets in another galaxy. As they navigate the harsh realities of space, Cooper is faced with heart-wrenching choices and a race against time to save his family and all of mankind.`,
    posterURL: "https://fr.web.img5.acsta.net/c_310_420/pictures/14/09/24/12/08/158828.jpg",
    rating: 8.7,
    trailerURL: "https://www.youtube.com/embed/zSWdZVtXT7E",
  },
  {
    id: 4,
    title: "Forrest Gump",
    description: `In this heartwarming journey, Forrest Gump, a man with a low IQ but a big heart, unknowingly influences key moments in American history while navigating challenges and finding love along the way. The film follows Forrest through several decades of American history, touching on events such as the Vietnam War, the Watergate scandal, and the rise of Apple computers. Despite his limited intellectual ability, Forrest becomes a war hero, a famous college football player, and an entrepreneur, all the while being deeply devoted to his childhood love, Jenny. His journey is a testament to the power of love, kindness, and fate.`,
    posterURL: "https://fr.web.img2.acsta.net/c_310_420/pictures/15/10/13/15/12/514297.jpg",
    rating: 8.8,
    trailerURL: "https://www.youtube.com/embed/bLvqoHBptjg",
  },
  {
    id: 5,
    title: "The Godfather",
    description: `In this gripping crime saga, Don Vito Corleone, the powerful patriarch of a mafia family, struggles to maintain control as his empire faces betrayal, violence, and the shifting loyalty of his sons. The story centers around the Corleone family, whose members are involved in organized crime in New York City. When Don Vito is attacked and nearly killed, his youngest son Michael, initially reluctant to be involved in the family business, is drawn into the world of crime. As Michael ascends to power, the family's legacy is threatened by betrayals, revenge, and the desire to protect those they love. The film explores themes of loyalty, power, and the cost of violence in a ruthless world.`,
    posterURL: "https://fr.web.img6.acsta.net/c_310_420/pictures/22/01/14/08/39/1848157.jpg",
    rating: 9.2,
    trailerURL: "https://www.youtube.com/embed/sY1S34973zA",
  },
  {
    id: 6,
    title: "The Dark Knight",
    description: `In this critically acclaimed sequel to Batman Begins, Gotham City is under siege by a new wave of crime led by the psychotic and anarchic Joker. Batman, played by Christian Bale, faces his greatest challenge as he battles against the Joker’s attempts to bring Gotham to its knees. The Joker tests Batman's moral code, forcing him to confront his own limits as he struggles to protect Gotham and the people he loves. This dark, intense film explores themes of chaos, justice, and the fine line between heroism and vigilantism.`,
    posterURL: "https://fr.web.img6.acsta.net/c_310_420/medias/nmedia/18/63/97/89/18949761.jpg",
    rating: 4.9,
    trailerURL: "https://www.youtube.com/embed/EXeTwQWrcwY",
  },
  {
    id: 7,
    title: "The Shawshank Redemption",
    description: `This gripping tale of friendship and hope follows Andy Dufresne, a man wrongly convicted of murder, as he spends years in Shawshank prison. During his time behind bars, Andy befriends fellow inmate Ellis "Red" Redding, and together they form a bond that transcends the harsh realities of prison life. Despite the oppressive environment, Andy maintains his belief in freedom and justice, using his intelligence and determination to make life better for himself and his fellow inmates. The film highlights the enduring power of hope and redemption.`,
    posterURL: "https://fr.web.img6.acsta.net/c_310_420/medias/nmedia/18/63/30/68/18686447.jpg",
    rating: 9.3,
    trailerURL: "https://www.youtube.com/embed/6hB3S9bIaco",
  },
  {
    id: 8,
    title: "The Lion King",
    description: `This Disney animated classic tells the story of Simba, a young lion cub who is destined to become king of the Pride Lands. However, after the death of his father Mufasa, Simba is tricked into thinking he is responsible for the tragedy and runs away from his kingdom. During his exile, Simba meets new friends and learns valuable life lessons. As he matures, he returns to reclaim his rightful place as king and restore balance to the Pride Lands, facing his past and embracing his destiny as the true king.`,
    posterURL: "https://fr.web.img6.acsta.net/c_310_420/pictures/19/02/25/12/06/2908996.jpg",
    rating: 8.5,
    trailerURL: "https://www.youtube.com/embed/4sj1MT05lAA",
  },
  {
    id: 9,
    title: "Avengers: Endgame",
    description: `In the thrilling conclusion to the Infinity Saga, the Avengers must come together to undo the devastating effects of Thanos' snap, which wiped out half of all life in the universe. The team works tirelessly to retrieve the Infinity Stones and reverse the damage caused by their previous battles. Each hero must confront their past, and some face sacrifices along the way. With high stakes and emotional moments, the final showdown between the Avengers and Thanos culminates in an epic battle that will forever change the fate of the universe.`,
    posterURL: "https://fr.web.img6.acsta.net/c_310_420/pictures/19/04/04/09/04/0472053.jpg",
    rating: 8.4,
    trailerURL: "https://www.youtube.com/embed/hA6hldpSTF8",
  },
  {
    id: 10,
    title: "The Matrix",
    description: `This groundbreaking science fiction film follows Neo, a computer hacker who discovers that the reality he perceives is actually a simulation created by machines to subjugate humanity. Neo is drawn into a rebellion against the machines, guided by Morpheus, a mentor who believes Neo is "The One" — the person prophesied to end the war between humans and machines. As Neo begins to understand his powers within the Matrix, he must face the forces trying to stop him and make the ultimate choice between saving humanity or the world he knows.`,
    posterURL: "https://fr.web.img6.acsta.net/c_310_420/medias/nmedia/00/02/53/34/affiche.jpg",
    rating: 8.7,
    trailerURL: "https://www.youtube.com/embed/vKQi3bBA1y8",
  },
  {
    id: 11,
    title: "Inception",
    description: `A skilled thief, Dom Cobb, who specializes in stealing secrets through the use of dream-sharing technology, is given a chance to have his criminal record erased if he can successfully perform an inception—planting an idea into a target's subconscious. With a team of specialists, Cobb embarks on a heist that takes them deep into layers of dreams. As the line between reality and dreams blurs, Cobb is forced to confront his own inner demons in order to complete the mission and return to his children.`,
    posterURL: "https://fr.web.img6.acsta.net/c_310_420/medias/nmedia/18/72/34/14/19476654.jpg",
    rating: 8.8,
    trailerURL: "https://www.youtube.com/embed/YoHD9XEInc0",
  },
  {
    id: 12,
    title: "Fight Club",
    description: `In this dark and thought-provoking film, a man (Edward Norton), dissatisfied with his life and suffering from insomnia, forms an underground fight club with the charismatic and anarchistic Tyler Durden (Brad Pitt). The club grows into a dangerous movement that challenges consumerism, conformity, and the modern capitalist society. As the protagonist uncovers disturbing truths about his own identity and the extent of Tyler's influence, the story explores themes of masculinity, identity, and self-destruction.`,
    posterURL: "https://fr.web.img4.acsta.net/c_310_420/pictures/23/12/07/09/17/5988972.jpg",
    rating: 8.8,
    trailerURL: "https://www.youtube.com/embed/qtRKdVHc-cE",
  },
  {
    id: 13,
    title: "Pulp Fiction",
    description: `Quentin Tarantino's iconic film weaves together multiple storylines, focusing on the lives of Los Angeles criminals. The film features intertwining narratives, including the lives of a hitman duo, Vincent Vega and Jules Winnfield, a mob boss's wife, and a boxer on the run. With sharp dialogue, nonlinear storytelling, and dark humor, "Pulp Fiction" explores themes of redemption, fate, and the randomness of life, all set to a memorable soundtrack.`,
    posterURL: "https://fr.web.img2.acsta.net/c_310_420/medias/nmedia/18/36/02/52/18846059.jpg",
    rating: 8.9,
    trailerURL: "https://www.youtube.com/embed/s7EdQ4FqbhY",
  },
  {
    id: 14,
    title: "The Lord of the Rings: The Return of the King",
    description: `The epic conclusion to the "Lord of the Rings" trilogy follows Frodo Baggins and his companions as they make their final stand against Sauron, the dark lord, in the battle for Middle-Earth. With the One Ring nearing its destruction, Frodo and Sam struggle to reach Mount Doom, while Aragorn, Legolas, and Gimli lead an army against Sauron's forces. The final film explores themes of friendship, sacrifice, and hope amidst overwhelming darkness.`,
    posterURL: "https://fr.web.img6.acsta.net/c_310_420/medias/nmedia/18/35/14/33/18366630.jpg",
    rating: 8.9,
    trailerURL: "https://www.youtube.com/embed/r5X-hFf6Bwo",
  },
  {
    id: 15,
    title: "Schindler's List",
    description: `This powerful and haunting film tells the true story of Oskar Schindler, a German businessman who saves over 1,100 Polish Jews during the Holocaust by employing them in his factory. As the atrocities of World War II unfold, Schindler's compassion and moral courage shine through, even as he faces the increasing threat of the Nazis. The film explores the horrors of the Holocaust while celebrating the impact of one individual's actions to save countless lives.`,
    posterURL: "https://fr.web.img4.acsta.net/c_310_420/pictures/19/03/14/10/37/5927961.jpg",
    rating: 9.3,
    trailerURL: "https://www.youtube.com/embed/gG22XNhtnoY",
  },
];

export default moviesData;
